# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

jquerycdn = true

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  siteStartYear = 2008
  description = "Unlocking the secrets to a fruitful relationship and unconditional love."
  keywords = ["Love and Relationships", "Love & Relationships", "愛と関係", "사랑과관계", "사랑과 관계", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "יהוחנן", "ᜌᜓᜃᜒ", "사요한", "謝雪矢（ゆきや）", "스노", "Seu-No", "SeuNo", "Snow", "Yohanan", "ᜌᜓᜑᜈᜈ᜔", "ᜌᜓᜑᜈᜈ᜕", "ᜌᜑᜓᜑᜈᜈ᜔", "ᜌᜑᜓᜑᜈᜈ᜕"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Love_and_Relationship.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  logo = "https://rsc.youronly.one/img/y/Love_and_Relationship.webp"
  home = "Home"
  # theme layout ( two layout is available, "1" and "2" )
  layout = "1"
  # Preloader
  #preloader = true
  # search
  search = true
  # about author
  #author_image = ""
  #bio = ""
  # Contact info
  #mobile = ""
  #email = ""
  #address = ""
  # Contact Form Action
  #contact_form_action = "#"

  # CSS Plugins
  [[plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[plugins.css]]
  link = "plugins/slick/slick.css"
  [[plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[plugins.js]]
  link = ""
  [[plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[plugins.js]]
  link = "plugins/headroom/headroom.js"
  [[plugins.js]]
  link = "plugins/instafeed/instafeed.min.js"
  [[plugins.js]]
  link = "plugins/masonry/masonry.js"
  [[plugins.js]]
  link = "plugins/reading-time/readingTime.min.js"
  [[plugins.js]]
  link = "plugins/smooth-scroll/smooth-scroll.js"
  [[plugins.js]]
  link = "plugins/search/fuse.min.js"
  [[plugins.js]]
  link = "plugins/search/mark.js"
  [[plugins.js]]
  link = "plugins/search/search.js"

  # Instagram feed
  [instafeed]
  enable = false
  access_token = "183794425326191|5734e2f164e94e3247f0f1499061c7b7"

  # cookies
  [cookies]
  enable = false
  expire_days = 2

  # social site
  [[social2]]
  icon = "fa fa-mastodon"
  link = "https://c.im/@youronlyone"

  [[social2]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/YourOnly.ONE.ofcl"

  [[social2]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/YourOnlyOne7"

  #[[social]]
  #icon = "ti-twitter-alt"
  #link = "https://twitter.com/YourOnlyONEofcl"

  #[[social]]
  #icon = "ti-instagram"
  #link = ""

  [[social2]]
  icon = "ti-youtube"
  link = "https://www.youtube.com/YourOnlyONEofcl"
### END: Theme Settings ###

### BGN: Hugo module settings ###
  ##### BGN: syndication #####
    ## Custom entries only work if placed in per-site params.toml ##
    [[sns]]
      url = 'blogspot.com'
      icon = 'blogspot.svg'
    [[sns]]
      url = 'bsky.app'
      icon = 'bluesky.svg'
    [[sns]]
      url = 'c.im'
      icon = 'mastodon.png'
    [[sns]]
      url = 'c.wtf'
      icon = 'rebased.svg'
    [[sns]]
      url = 'catodon.social'
      icon = 'catodon.png'
    [[sns]]
      url = 'diasp.org'
      icon = 'diaspora.svg'
    [[sns]]
      url = 'ebin.club'
      icon = 'fediverse.svg'
    [[sns]]
      url = 'facebook.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fb.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fedia.io'
      icon = 'mbin.svg'
    [[sns]]
      url = 'fedia.social'
      icon = 'iceshrimp.png'
    [[sns]]
      url = 'instagram.com'
      icon = 'instagram.svg'
    [[sns]]
      url = 'mastodon.online'
      icon = 'mastodon.png'
    [[sns]]
      url = 'mastodon.social'
      icon = 'mastodon.png'
    [[sns]]
      url = 'naver.com'
      icon = 'naver.png'
    [[sns]]
      url = 'p.lu'
      icon = 'peertube.svg'
    [[sns]]
      url = 'pixelfed.social'
      icon = 'pixelfed.svg'
    [[sns]]
      url = 'plurk.com'
      icon = 'plurk.svg'
    [[sns]]
      url = 'reddit.com'
      icon = 'reddit.svg'
    [[sns]]
      url = 'socialhome.network'
      icon = 'socialhome-black.svg'
    [[sns]]
      url = 'spoutible.com'
      icon = 'spoutible.png'
    [[sns]]
      url = 'threads.net'
      icon = 'threads.svg'
    [[sns]]
      url = 'tumblr.com'
      icon = 'tumblr.svg'
    [[sns]]
      url = 'twitter.com'
      icon = 'twitter.svg'
    [[sns]]
      url = 'wordpress.com'
      icon = 'wordpress.svg'
    [[sns]]
      url = 'write.as'
      icon = 'writefreely.png'
    [[sns]]
      url = 'x.com'
      icon = 'x.svg'
    [[sns]]
      url = 'youtube.com'
      icon = 'youtube.svg'
    [[sns]]
      url = 'is.youronly.one'
      icon = 'bluesky.svg'
    [[sns]]
      url = 't.youronly.one'
      icon = 'tumblr.svg'
  ##### END: syndication #####
### END: Hugo module settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2008-02-23"
    isblog = true
    sameas = [
      "https://www.facebook.com/YourOnlyOne7",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]

  [tools]
    #onesignal = "79058a23-5e2c-4862-926f-37d20de118e5"
### END: Other Settings ###
