# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

jquerycdn = true

favicon_mstilecolor = "#2b5797"

### BGN: Structured Data ###
  siteStartYear = 2008
  description = "Unlocking the secrets to a fruitful relationship and unconditional love."
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ", "Love and Relationships", "Love & Relationships"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/Love_and_Relationship.webp"]
### END: Structured Data ###

### BGN: Theme Settings ###
  logo = "https://rsc.youronly.one/img/y/Love_and_Relationship.webp"
  home = "Home"
  # theme layout ( two layout is available, "1" and "2" )
  layout = "1"
  # Preloader
  #preloader = true
  # search
  search = true
  # about author
  #author_image = ""
  #bio = ""
  # Contact info
  #mobile = ""
  #email = ""
  #address = ""
  # Contact Form Action
  #contact_form_action = "#"

  # CSS Plugins
  [[plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[plugins.css]]
  link = "plugins/slick/slick.css"
  [[plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[plugins.js]]
  link = ""
  [[plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[plugins.js]]
  link = "plugins/headroom/headroom.js"
  [[plugins.js]]
  link = "plugins/instafeed/instafeed.min.js"
  [[plugins.js]]
  link = "plugins/masonry/masonry.js"
  [[plugins.js]]
  link = "plugins/reading-time/readingTime.min.js"
  [[plugins.js]]
  link = "plugins/smooth-scroll/smooth-scroll.js"
  [[plugins.js]]
  link = "plugins/search/fuse.min.js"
  [[plugins.js]]
  link = "plugins/search/mark.js"
  [[plugins.js]]
  link = "plugins/search/search.js"

  # Instagram feed
  [instafeed]
  enable = false
  access_token = "183794425326191|5734e2f164e94e3247f0f1499061c7b7"

  # cookies
  [cookies]
  enable = false
  expire_days = 2

  # social site
  [[social]]
  icon = "fa fa-mastodon"
  link = "https://c.im/@youronlyone"

  [[social]]
  icon = "ti-facebook"
  link = "https://facebook.com/YourOnly.ONE.ofcl"

  [[social]]
  icon = "ti-facebook"
  link = "https://facebook.com/YourOnlyOne7"

  #[[social]]
  #icon = "ti-twitter-alt"
  #link = "https://twitter.com/YourOnlyONEofcl"

  #[[social]]
  #icon = "ti-instagram"
  #link = ""

  [[social]]
  icon = "ti-youtube"
  link = "https://youtube.com/YourOnlyONEofcl"
### END: Theme Settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2008-02-23"
    isblog = true
    sameas = [
      "https://facebook.com/YourOnlyOne7",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://hashi.icu/@YourOnlyOne",
      "https://youtube.com/@YourOnlyOneOfcl",
      "https://facebook.com/YourOnly.ONE.ofcl"
    ]

  [tools]
    #onesignal = "79058a23-5e2c-4862-926f-37d20de118e5"
### END: Other Settings ###
